import { createContext, useContext, useState } from 'react';

const AppContext = createContext();

export function AppProvider({ children }) {
    const [currentBorrower, setCurrentBorrower] = useState({
        name: 'TechNova Manufacturing Pvt Ltd',
        industry: 'Industrial Equipment',
        status: 'In Progress',
    });

    // This will hold the massive JSON payload generated by Gemini for every module
    const [globalAIState, setGlobalAIState] = useState(null);

    return (
        <AppContext.Provider value={{ currentBorrower, setCurrentBorrower, globalAIState, setGlobalAIState }}>
            {children}
        </AppContext.Provider>
    );
}

export const useAppContext = () => useContext(AppContext);
